version: '3'

services:
  confluence:
    image: atlassian/confluence-server
    container_name: confluence
    hostname: confluence
    ports:
      - 8090:8090
    volumes:
      - /opt/atlassian/data/confluence:/var/atlassian/application-data/confluence
      - ./server.xml:/opt/atlassian/etc/server.xml.j2
    networks:
      - atlassianNet

networks:
  atlassianNet:
    external: true
    