version: '3'
services:
  proxy:
    container_name: nginx
    hostname: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./config:/etc/nginx
    networks:
      - atlassianNet

networks:
  atlassianNet:
    external: true