CREATE USER jira WITH ENCRYPTED PASSWORD 'testing123123';

CREATE DATABASE jiradb ENCODING 'UNICODE' LC_COLLATE 'C' TEMPLATE template0;
GRANT ALL PRIVILEGES ON DATABASE jiradb TO jira;

CREATE USER confluence WITH ENCRYPTED PASSWORD 'testing123123';

CREATE DATABASE confluencedb ENCODING 'UTF8' LC_COLLATE 'en_US.UTF8' TEMPLATE template0;
GRANT ALL PRIVILEGES ON DATABASE confluencedb TO confluence;